# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2055312c75a4c131cc285d442adc9c584770a6bd8ff402abc534173ae72fa693cbbdf17672a13d1ee6ff210384d559ad0f6852d44afaa1266f8e6c796fcf9fa0

test:
  secret_key_base: a2bb76debd02424c9cd9ae851033a9f12fe7ba0ededf5edbb43e73f9a30774215d7acd6273032be8d2218e885f295d7a370d4d78cb2d1ab59a16fcebea96f1de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
